[package]
name = "rejumon"
version = "0.2.0"
authors = ["Raphaël Zumer <rzumer@tebako.net>"]
description = "ドラゴンクエストⅠ・Ⅱ　ふっかつのじゅもん　修正ツール"
license = "WTFPL"
repository = "https://github.com/rzumer/rejumon"
edition = "2021"

[dependencies]
bitstream-io = "2.2"
prettytable-rs = "^0.10"
colored = "2.1"
