[licenses]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
unlicensed = "deny"
confidence-threshold = 0.8
allow = [
    "WTFPL",
    "MIT",
    "MPL-2.0",
    "Apache-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]
